# -*- coding: utf-8 -*-
"""cv.lab3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tCwyeGdQn313I30eMToJoc7Z4fa70D6R
"""

import cv2
from matplotlib import pyplot as plt
import numpy as np

def show_comparison(original,blur3,blur5,blur7,blur11):
  plt.figure(figsize=(12,10))
  plt.subplot(3,2,1)
  plt.imshow(original,cmap='gray')
  plt.title('original gray scale image')
  plt.axis('off')

  plt.subplot(3,2,2)
  plt.imshow(blur3,cmap='gray')
  plt.title("Average filter(3*3)")
  plt.axis('off')

  plt.subplot(3,2,3)
  plt.imshow(blur5,cmap='gray')
  plt.title("Average filter(5*5)")
  plt.axis('off')

  plt.subplot(3,2,4)
  plt.imshow(blur7,cmap='gray')
  plt.title("Average filter(7*7)")
  plt.axis('off')

  plt.subplot(3,2,5)
  plt.imshow(blur11,cmap='gray')
  plt.title("Average filter(11*11)")
  plt.axis('off')

img= cv2.imread('/content/blur.jpg',0)
#img= cv2.imread('/content/to.webp',0)
if img is None:
  print('error:image not found')
else:
    kernel_3x3 = np.ones((3,3),np.float32)/9
    kernel_5x5 = np.ones((5,5),np.float32)/25
    kernel_7x7 = np.ones((7,7),np.float32)/49
    kernel_11x11 = np.ones((11,11),np.float32)/121
    blur_3 = cv2.filter2D(img,-1,kernel_3x3)
    blur_5 = cv2.filter2D(img,-1,kernel_5x5)
    blur_7 = cv2.filter2D(img,-1,kernel_7x7)
    blur_11 = cv2.filter2D(img,-1,kernel_11x11)
    show_comparison(img,blur_3,blur_5,blur_7,blur_11)