# -*- coding: utf-8 -*-
"""cv.lab3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tCwyeGdQn313I30eMToJoc7Z4fa70D6R
"""
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

def average_filter(image, kernel_size):
    pad = kernel_size // 2
    padded = np.pad(image, pad, mode='edge')
    output = np.zeros_like(image, dtype=np.float32)

    for i in range(image.shape[0]):
        for j in range(image.shape[1]):
            region = padded[i:i+kernel_size, j:j+kernel_size]
            output[i, j] = np.mean(region)

    return output.astype(np.uint8)


def show_comparison(original, blur3, blur5, blur7):
    plt.figure(figsize=(12, 10))

    # Original Image
    plt.subplot(2, 2, 1)
    plt.imshow(original, cmap='gray')
    plt.title("Original Grayscale Image")
    plt.axis('off')

    # 3x3 Kernel
    plt.subplot(2, 2, 2)
    plt.imshow(blur3, cmap='gray')
    plt.title("Average Filter (3x3)")
    plt.axis('off')

    # 5x5 Kernel
    plt.subplot(2, 2, 3)
    plt.imshow(blur5, cmap='gray')
    plt.title("Average Filter (5x5)")
    plt.axis('off')

    # 7x7 Kernel
    plt.subplot(2, 2, 4)
    plt.imshow(blur7, cmap='gray')
    plt.title("Average Filter (7x7)")
    plt.axis('off')

    plt.tight_layout()
    plt.show()


# Read image in grayscale
img = np.array(Image.open('input_image.jpg').convert('L'))

# Apply average filters
blur_3x3 = average_filter(img, 3)
blur_5x5 = average_filter(img, 5)
blur_7x7 = average_filter(img, 7)

# Display results
show_comparison(img, blur_3x3, blur_5x5, blur_7x7)

  
   
